#!/bin/bash
source ./bits/bootstrap/logging
set -euo pipefail ; IFS=$'\n\t'

#-----------
# Configurations
#-----------

ERLANG_VERSION=${ERLANG_VERSION-17.5-1}
ERLANG_DISPLAY=${ERLANG_DISPLAY-standalone} # or internal

LOG_DIR=${LOG_DIR-/var/log}
export SRC_DIR=${SRC_DIR-/var/src}
export ERLANG_LOG_DIR=${ERLANG_LOG_DIR-$LOG_DIR/elixir}

LAUNCHER_OWNER=${LAUNCHER_OWNER-$USER}
export LAUNCHER_DIR=${LAUNCHER_DIR-/var/local}
export ERLANG_LAUNCHER_DIR=${ERLANG_LAUNCHER_DIR-$LAUNCHER_DIR/elixir/$ERLANG_VERSION}

#-----------
# Install Script
#-----------

if [[ "$ERLANG_DISPLAY" == "standalone" ]]; then
  notify "Install Erlang ($ERLANG_VERSION)..."
else
  notify "  -- install Erlang ($ERLANG_VERSION)..."
fi

DIR=./bits/erlang ./bits/bootstrap/cleanup

if [[ "$ERLANG_DISPLAY" == "standalone" ]]; then
  notify "DONE, Install Erlang."
else
  notify "  -- DONE, Install Erlang."
fi
